from django.urls import path

from .views import (
    BOQCSVDownloadAPIView,
    BOQConversationAPIView,
    BOQGenerateAPIView,
    BOQManualVersionAPIView,
    BOQSelectAPIView,
    BOQSkipAPIView,
    BOQVersionListAPIView,
    ConversationMessageDeleteAPIView,
    FloorPlanConversationAPIView,
    FloorPlanEditAPIView,
    FloorPlanGenerateAPIView,
    FloorPlanHistoryAPIView,
    FloorPlanSelectAPIView,
    FloorPlanUploadAPIView,
    ProcessingJobDetailAPIView,
    ProjectArchiveAPIView,
    ProjectAssetDownloadAPIView,
    ProjectAssetListAPIView,
    ProjectDetailAPIView,
    ProjectDocumentDetailAPIView,
    ProjectDocumentListCreateAPIView,
    ProjectFinishAPIView,
    ProjectListCreateAPIView,
    ProjectOutputAPIView,
    StepTwoInputUploadAPIView,
    ThreeDAngleAPIView,
    ThreeDConversationAPIView,
    ThreeDEditAPIView,
    ThreeDGenerateAPIView,
    ThreeDHistoryAPIView,
    ThreeDSelectAPIView,
)


app_name = 'projects'

urlpatterns = [
    path('', ProjectListCreateAPIView.as_view(), name='list-create'),
    path('jobs/<uuid:job_id>/', ProcessingJobDetailAPIView.as_view(), name='job-detail'),
    path('<uuid:project_id>/', ProjectDetailAPIView.as_view(), name='detail'),
    path(
        '<uuid:project_id>/output/',
        ProjectOutputAPIView.as_view(),
        name='output',
    ),
    path(
        '<uuid:project_id>/finish/',
        ProjectFinishAPIView.as_view(),
        name='finish',
    ),
    path(
        '<uuid:project_id>/conversations/messages/<uuid:message_id>/',
        ConversationMessageDeleteAPIView.as_view(),
        name='message-delete',
    ),
    path(
        '<uuid:project_id>/step-1/conversation/',
        FloorPlanConversationAPIView.as_view(),
        name='floor-plan-conversation',
    ),
    path(
        '<uuid:project_id>/step-1/history/',
        FloorPlanHistoryAPIView.as_view(),
        name='floor-plan-history',
    ),
    path(
        '<uuid:project_id>/step-1/upload/',
        FloorPlanUploadAPIView.as_view(),
        name='floor-plan-upload',
    ),
    path(
        '<uuid:project_id>/step-1/generate/',
        FloorPlanGenerateAPIView.as_view(),
        name='floor-plan-generate',
    ),
    path(
        '<uuid:project_id>/step-1/edit/',
        FloorPlanEditAPIView.as_view(),
        name='floor-plan-edit',
    ),
    path(
        '<uuid:project_id>/step-1/versions/<uuid:version_id>/select/',
        FloorPlanSelectAPIView.as_view(),
        name='floor-plan-select',
    ),
    path(
        '<uuid:project_id>/step-1/versions/<uuid:version_id>/approve/',
        FloorPlanSelectAPIView.as_view(),
        name='floor-plan-approve',
    ),
    path(
        '<uuid:project_id>/step-2/input/',
        StepTwoInputUploadAPIView.as_view(),
        name='step-two-input',
    ),
    path(
        '<uuid:project_id>/step-2/history/',
        ThreeDHistoryAPIView.as_view(),
        name='three-d-history',
    ),
    path(
        '<uuid:project_id>/step-2/conversation/',
        ThreeDConversationAPIView.as_view(),
        name='three-d-conversation',
    ),
    path(
        '<uuid:project_id>/step-2/generate/',
        ThreeDGenerateAPIView.as_view(),
        name='three-d-generate',
    ),
    path(
        '<uuid:project_id>/step-2/edit/',
        ThreeDEditAPIView.as_view(),
        name='three-d-edit',
    ),
    path(
        '<uuid:project_id>/step-2/angle/',
        ThreeDAngleAPIView.as_view(),
        name='three-d-angle',
    ),
    path(
        '<uuid:project_id>/step-2/versions/<uuid:version_id>/select/',
        ThreeDSelectAPIView.as_view(),
        name='three-d-select',
    ),
    path(
        '<uuid:project_id>/step-2/versions/<uuid:version_id>/approve/',
        ThreeDSelectAPIView.as_view(),
        name='three-d-approve',
    ),
    path(
        '<uuid:project_id>/step-3/conversation/',
        BOQConversationAPIView.as_view(),
        name='boq-conversation',
    ),
    path(
        '<uuid:project_id>/step-3/generate/',
        BOQGenerateAPIView.as_view(),
        name='boq-generate',
    ),
    path(
        '<uuid:project_id>/step-3/versions/',
        BOQVersionListAPIView.as_view(),
        name='boq-version-list',
    ),
    path(
        '<uuid:project_id>/step-3/versions/manual/',
        BOQManualVersionAPIView.as_view(),
        name='boq-version-manual',
    ),
    path(
        '<uuid:project_id>/step-3/versions/<uuid:version_id>/select/',
        BOQSelectAPIView.as_view(),
        name='boq-select',
    ),
    path(
        '<uuid:project_id>/step-3/versions/<uuid:version_id>/approve/',
        BOQSelectAPIView.as_view(),
        name='boq-approve',
    ),
    path(
        '<uuid:project_id>/step-3/versions/<uuid:version_id>/download-csv/',
        BOQCSVDownloadAPIView.as_view(),
        name='boq-download-csv',
    ),
    path(
        '<uuid:project_id>/step-3/skip/',
        BOQSkipAPIView.as_view(),
        name='boq-skip',
    ),
    path(
        '<uuid:project_id>/step-3/documents/',
        ProjectDocumentListCreateAPIView.as_view(),
        name='document-list-create',
    ),
    path(
        '<uuid:project_id>/step-3/documents/<uuid:document_id>/',
        ProjectDocumentDetailAPIView.as_view(),
        name='document-detail',
    ),
    path(
        '<uuid:project_id>/assets/',
        ProjectAssetListAPIView.as_view(),
        name='asset-list',
    ),
    path(
        '<uuid:project_id>/assets/<uuid:asset_id>/download/',
        ProjectAssetDownloadAPIView.as_view(),
        name='asset-download',
    ),
    path(
        '<uuid:project_id>/download-all/',
        ProjectArchiveAPIView.as_view(),
        name='download-all',
    ),
]
