# Generated by Django 5.2.6 on 2026-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='purpose',
            field=models.CharField(choices=[('PASSWORD_CHANGE', 'Password change'), ('PASSWORD_RESET', 'Password reset'), ('ACCOUNT_DELETE', 'Account deletion')], max_length=30),
        ),
    ]
