# Generated by Django 5.2.6 on 2026-08-29 03:57

import django.db.models.deletion
import projects.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('THREE_D', '3D generation'), ('BOQ', 'BOQ generation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('FLOOR_PLAN_GENERATE', 'Generate 2D floor plan'), ('FLOOR_PLAN_EDIT', 'Edit 2D floor plan'), ('THREE_D_GENERATE', 'Generate 3D image'), ('THREE_D_EDIT', 'Edit 3D image'), ('BOQ_GENERATE', 'Generate BOQ'), ('PROJECT_ARCHIVE', 'Build project archive')], max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FloorPlanVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('GENERATED', 'Generated'), ('EDITED', 'Edited')], max_length=20)),
                ('prompt', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_versions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='projects.floorplanversion')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_version', to='projects.processingjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOQVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('GENERATED', 'AI generated'), ('MANUAL', 'Manual edit')], max_length=20)),
                ('structured_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_versions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='projects.boqversion')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_versions', to='projects.conversationmessage')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boq_version', to='projects.processingjob')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('workflow', models.CharField(choices=[('COMPLETE', 'Complete workflow'), ('STEP_1_ONLY', 'Step 1 only'), ('STEP_2_ONLY', 'Step 2 only'), ('STEP_3_ONLY', 'Step 3 only')], max_length=20)),
                ('step_1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_3_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('selected_boq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.boqversion')),
                ('selected_floor_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.floorplanversion')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='processingjob',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='floorplanversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plan_versions', to='projects.project'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='boqversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_versions', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FLOOR_PLAN', '2D floor plan'), ('THREE_D_IMAGE', '3D image'), ('MASK', '3D edit mask'), ('BOQ_FILE', 'BOQ file'), ('UPLOAD', 'Uploaded file'), ('ARCHIVE', 'Project archive')], max_length=30)),
                ('file', models.FileField(upload_to=projects.models.project_asset_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processingjob',
            name='output_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_jobs', to='projects.projectasset'),
        ),
        migrations.AddField(
            model_name='floorplanversion',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_versions', to='projects.projectasset'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='messages', to='projects.projectasset'),
        ),
        migrations.CreateModel(
            name='ThreeDVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('GENERATED', 'Generated'), ('EDITED', 'Edited')], max_length=20)),
                ('instruction', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_d_versions', to=settings.AUTH_USER_MODEL)),
                ('floor_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='three_d_versions', to='projects.floorplanversion')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_d_versions', to='projects.projectasset')),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_d_version', to='projects.processingjob')),
                ('mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masked_three_d_edits', to='projects.projectasset')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='projects.threedversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='three_d_versions', to='projects.project')),
                ('prompt_message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='three_d_version', to='projects.conversationmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='selected_three_d',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.threedversion'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('project', 'kind'), name='one_conversation_per_project_kind'),
        ),
        migrations.AddConstraint(
            model_name='boqversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_boq_version_per_project'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_project_name_per_owner'),
        ),
    ]
