# Generated by Django 5.2.6 on 2026-08-29 04:03

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_name_per_owner',
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['project', 'status', 'created_at'], name='projects_pr_project_c9fb91_idx'),
        ),
        migrations.AddConstraint(
            model_name='processingjob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='processing_job_progress_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='unique_project_name_per_owner'),
        ),
    ]
