# Generated by Django 5.2.6 on 2026-08-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_unique_project_name_per_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='workflow',
            field=models.CharField(choices=[('COMPLETE', 'Complete workflow'), ('STEP_1_ONLY', 'Step 1 only'), ('STEP_2_ONLY', 'Step 2 only'), ('STEP_3_ONLY', 'Step 3 only')], default='COMPLETE', max_length=20),
        ),
    ]
