# Generated by Django 5.2.6 on 2026-08-30 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='floorplanversion',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floorplanversion',
            name='mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masked_floor_plan_edits', to='projects.projectasset'),
        ),
        migrations.AddField(
            model_name='floorplanversion',
            name='prompt_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_plan_version', to='projects.conversationmessage'),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='boq_skipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threedversion',
            name='angle',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('ISOMETRIC_45', 'Isometric 45°')], default='ORIGINAL', max_length=30),
        ),
        migrations.AddField(
            model_name='threedversion',
            name='render_style',
            field=models.CharField(choices=[('SKETCHUP', 'SketchUp'), ('PHOTOREALISTIC', 'Photorealistic')], default='SKETCHUP', max_length=30),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='kind',
            field=models.CharField(choices=[('FLOOR_PLAN', '2D floor-plan generation'), ('THREE_D', '3D generation'), ('BOQ', 'BOQ generation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('FLOOR_PLAN_GENERATE', 'Generate 2D floor plan'), ('FLOOR_PLAN_EDIT', 'Edit 2D floor plan'), ('THREE_D_GENERATE', 'Generate 3D image'), ('THREE_D_EDIT', 'Edit 3D image'), ('THREE_D_ANGLE', 'Generate 3D viewing angle'), ('BOQ_GENERATE', 'Generate BOQ'), ('PROJECT_ARCHIVE', 'Build project archive')], max_length=40),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='kind',
            field=models.CharField(choices=[('FLOOR_PLAN', '2D floor plan'), ('THREE_D_IMAGE', '3D image'), ('MASK', '3D edit mask'), ('BOQ_FILE', 'BOQ file'), ('DOCUMENT', 'Project document'), ('UPLOAD', 'Uploaded file'), ('ARCHIVE', 'Project archive')], max_length=30),
        ),
        migrations.AlterField(
            model_name='threedversion',
            name='prompt_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_d_version', to='projects.conversationmessage'),
        ),
        migrations.AlterField(
            model_name='threedversion',
            name='source',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('EDITED', 'Edited'), ('ANGLE', 'Viewing angle')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('GENERAL', 'General document'), ('PROJECT_BRIEF', 'Project brief'), ('STRUCTURAL_DRAWING', 'Structural drawing'), ('ESTIMATION', 'Estimation'), ('MATERIAL_SPECIFICATION', 'Material specification'), ('THREE_D_MODEL', '3D model'), ('OTHER', 'Other')], default='GENERAL', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='projects.projectasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
