# Generated by Django 5.2.17 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_conversationmessage_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(
                choices=[
                    ('FLOOR_PLAN_GENERATE', 'Generate 2D floor plan'),
                    ('FLOOR_PLAN_EDIT', 'Edit 2D floor plan'),
                    ('FLOOR_PLAN_ANALYZE', 'Extract floor-plan geometry'),
                    ('THREE_D_GENERATE', 'Generate 3D image'),
                    ('THREE_D_EDIT', 'Edit 3D image'),
                    ('THREE_D_ANGLE', 'Generate 3D viewing angle'),
                    ('BOQ_GENERATE', 'Generate BOQ'),
                    ('PROJECT_ARCHIVE', 'Build project archive'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='projectasset',
            name='kind',
            field=models.CharField(
                choices=[
                    ('FLOOR_PLAN', '2D floor plan'),
                    ('THREE_D_IMAGE', '3D image'),
                    ('THREE_D_SNAPSHOT', 'Frontend WebGL snapshot'),
                    ('MASK', '3D edit mask'),
                    ('BOQ_FILE', 'BOQ file'),
                    ('DOCUMENT', 'Project document'),
                    ('UPLOAD', 'Uploaded file'),
                    ('ARCHIVE', 'Project archive'),
                ],
                max_length=30,
            ),
        ),
    ]
