# Generated by Django 5.2.17 on 2026-08-31 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_ai_pipeline_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedversion',
            name='floor_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three_d_versions', to='projects.floorplanversion'),
        ),
    ]
