# Generated by Django 5.2.17 on 2026-08-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_threedversion_floor_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('GENERAL', 'General document'), ('PROJECT_BRIEF', 'Project brief'), ('STRUCTURAL_DRAWING', 'Structural drawing'), ('ESTIMATION', 'Estimation'), ('MATERIAL_SPECIFICATION', 'Material specification'), ('THREE_D_MODEL', '3D model'), ('MEP_DRAWING', 'MEP Drawing'), ('HVAC_DRAWING', 'HVAC Drawing'), ('DOOR_WINDOW_SCHEDULE', 'Door & Window Schedule'), ('OTHER', 'Other')], default='GENERAL', max_length=40),
        ),
    ]
