# Generated by Django 5.2.17 on 2026-09-04 20:53

import bim.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BimSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=bim.models.bim_source_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=150)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('image_width', models.PositiveIntegerField(default=0)),
                ('image_height', models.PositiveIntegerField(default=0)),
                ('source_kind', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bim_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BimExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('quality', models.JSONField(blank=True, default=dict)),
                ('record', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=1)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bim_extractions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='bim.bimsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bimsource',
            index=models.Index(fields=['owner', '-created_at'], name='bim_bimsour_owner_i_dd4487_idx'),
        ),
        migrations.AddIndex(
            model_name='bimextraction',
            index=models.Index(fields=['source', '-created_at'], name='bim_bimextr_source__3e7b27_idx'),
        ),
        migrations.AddIndex(
            model_name='bimextraction',
            index=models.Index(fields=['status', 'created_at'], name='bim_bimextr_status_8d6175_idx'),
        ),
        migrations.AddConstraint(
            model_name='bimextraction',
            constraint=models.CheckConstraint(condition=models.Q(('progress__lte', 100)), name='bim_extraction_progress_lte_100'),
        ),
        migrations.AddConstraint(
            model_name='bimextraction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'PROCESSING'])), fields=('source',), name='one_active_bim_extraction_per_source'),
        ),
    ]
