"""The BIM plan contract — this app's own JSON, deliberately separate.

WHY A SECOND SCHEMA EXISTS
--------------------------
`app/ai/floorplan_schema.py` already models a floor plan, and Step 2's render
pipeline depends on its exact shape. That schema is a *rendering* contract: it
describes enough of a plan to prompt an image model. This one is an *authoring*
contract: it has to survive being turned into real BIM elements, edited element
by element in a browser, and rebuilt. Those needs conflict in three places, so
sharing one model would have meant changing the rendering contract:

  1. Openings here reference their wall by **id**, not by list index. An index
     is stable only while nobody edits the plan; delete one wall and every
     opening after it silently moves to the wrong host. Every element therefore
     carries a stable id that survives edits, reorderings and rebuilds.
  2. Everything is **multi-level**. A house plan and a four-storey building are
     the same document here, with one `Level` or four.
  3. Every value the extractor did not actually read off the drawing is
     recorded in `assumptions`, so the UI can mark it as a guess and the user
     can correct it. A rendering prompt has no use for that; an editor cannot
     work without it.

Nothing in this module imports from `app.ai` or `projects`, and nothing there
imports from here. Deleting the `bim` package removes this contract and
everything built on it, and leaves Step 1/2/3 untouched.

COORDINATE SYSTEM
-----------------
Origin bottom-left, +x right, +y up, +z up. Units are **meters** throughout,
matching the rest of the product. Elevations are absolute (ground floor = 0.0).
"""
from __future__ import annotations

import re
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

SCHEMA_VERSION = "1.0"

Point = Tuple[float, float]

# Element ids are generated by the extractor and referenced by openings, by the
# override system and by the viewer's selection state, so they are constrained
# rather than free text: a prefix, then digits. Anything else is a sign the
# model invented a reference rather than pointing at a real element.
_ID_PATTERN = re.compile(r"^[A-Z]{1,3}[0-9]{1,4}$")


class BuildingType(str, Enum):
    """What kind of building this plan is.

    Drives the per-type defaults below. `OTHER` is not a failure — it means the
    plan did not read as any of the named types, and the generic defaults
    apply. The list is deliberately short: every extra type is another set of
    defaults to justify, and a wrong type is worse than a generic one.
    """

    HOUSE = "house"
    APARTMENT = "apartment"
    OFFICE = "office"
    SHOP = "shop"
    RESTAURANT = "restaurant"
    WAREHOUSE = "warehouse"
    SCHOOL = "school"
    CLINIC = "clinic"
    HOTEL = "hotel"
    MIXED_USE = "mixed_use"
    OTHER = "other"


class WallType(str, Enum):
    EXTERIOR = "exterior"
    INTERIOR = "interior"
    PARTITION = "partition"
    RETAINING = "retaining"


class OpeningType(str, Enum):
    DOOR = "door"
    DOUBLE_DOOR = "double_door"
    SLIDING_DOOR = "sliding_door"
    WINDOW = "window"
    # A hole in a wall with no leaf — an archway, a pass-through, a shop front
    # opening. Common in the plans this has to handle and not expressible as
    # either a door or a window.
    OPENING = "opening"


class Confidence(str, Enum):
    """Where a value came from. The UI renders these three differently."""

    # Read off the drawing — a printed dimension, a scale bar, a labelled room.
    MEASURED = "measured"
    # Derived from something else that was measured (a wall length scaled from
    # a known overall dimension).
    INFERRED = "inferred"
    # Not present in the drawing at all; a default was applied.
    ASSUMED = "assumed"


class ScaleSource(str, Enum):
    DIMENSION_STRING = "dimension_string"  # "20.00 m" printed on the plan
    SCALE_BAR = "scale_bar"
    SCALE_RATIO = "scale_ratio"  # "1:100"
    ROOM_LABEL_AREA = "room_label_area"  # "Bedroom 14.2 m²"
    DOOR_HEURISTIC = "door_heuristic"  # a standard 0.9 m door as the ruler
    UNKNOWN = "unknown"


# --------------------------------------------------------------------------
# Per-building-type defaults.
#
# These are what fills in a value the drawing does not state. Every one of them
# lands in `BimPlan.assumptions` when it is used, so nothing here is silent.
#
# Sources are ordinary construction norms, not a standards body: residential
# floor-to-floor around 3.0 m with a 2.7 m clear height, commercial taller,
# warehouse taller again. They exist to produce a *plausible* model on the first
# pass, not a correct one — correctness comes from the user editing them.
# --------------------------------------------------------------------------
class TypeDefaults(BaseModel):
    model_config = ConfigDict(frozen=True)

    wall_height: float
    floor_to_floor: float
    exterior_thickness: float
    interior_thickness: float
    partition_thickness: float
    slab_thickness: float
    door_height: float
    door_width: float
    window_height: float
    window_sill: float


_GENERIC_DEFAULTS = TypeDefaults(
    wall_height=2.7,
    floor_to_floor=3.0,
    exterior_thickness=0.23,
    interior_thickness=0.15,
    partition_thickness=0.10,
    slab_thickness=0.15,
    door_height=2.1,
    door_width=0.9,
    window_height=1.2,
    window_sill=0.9,
)

TYPE_DEFAULTS: Dict[BuildingType, TypeDefaults] = {
    BuildingType.HOUSE: _GENERIC_DEFAULTS,
    BuildingType.APARTMENT: _GENERIC_DEFAULTS,
    BuildingType.OFFICE: _GENERIC_DEFAULTS.model_copy(
        update={
            "wall_height": 3.0,
            "floor_to_floor": 3.6,
            "window_height": 1.5,
            "window_sill": 0.8,
            "partition_thickness": 0.10,
        }
    ),
    BuildingType.SHOP: _GENERIC_DEFAULTS.model_copy(
        update={
            "wall_height": 3.2,
            "floor_to_floor": 3.8,
            "door_width": 1.2,
            "window_height": 2.1,
            "window_sill": 0.3,  # shopfront glazing runs near the floor
        }
    ),
    BuildingType.RESTAURANT: _GENERIC_DEFAULTS.model_copy(
        update={"wall_height": 3.2, "floor_to_floor": 3.8, "door_width": 1.0}
    ),
    BuildingType.WAREHOUSE: _GENERIC_DEFAULTS.model_copy(
        update={
            "wall_height": 6.0,
            "floor_to_floor": 6.5,
            "exterior_thickness": 0.25,
            "slab_thickness": 0.20,
            "door_width": 3.0,
            "door_height": 3.5,
            "window_sill": 2.4,
        }
    ),
    BuildingType.SCHOOL: _GENERIC_DEFAULTS.model_copy(
        update={"wall_height": 3.2, "floor_to_floor": 3.8, "door_width": 1.0}
    ),
    BuildingType.CLINIC: _GENERIC_DEFAULTS.model_copy(
        update={"wall_height": 3.0, "floor_to_floor": 3.6, "door_width": 1.1}
    ),
    BuildingType.HOTEL: _GENERIC_DEFAULTS.model_copy(
        update={"wall_height": 2.8, "floor_to_floor": 3.3}
    ),
    BuildingType.MIXED_USE: _GENERIC_DEFAULTS.model_copy(
        update={"wall_height": 3.0, "floor_to_floor": 3.6}
    ),
    BuildingType.OTHER: _GENERIC_DEFAULTS,
}


def defaults_for(building_type: BuildingType) -> TypeDefaults:
    return TYPE_DEFAULTS.get(building_type, _GENERIC_DEFAULTS)


# --------------------------------------------------------------------------
# Elements
# --------------------------------------------------------------------------
class _Element(BaseModel):
    """Shared id handling. Not used directly."""

    model_config = ConfigDict(extra="ignore")

    id: str

    @field_validator("id")
    @classmethod
    def _well_formed_id(cls, value: str) -> str:
        value = value.strip().upper()
        if not _ID_PATTERN.match(value):
            raise ValueError(
                f"id {value!r} is malformed; expected a short prefix and digits, e.g. 'W001'"
            )
        return value


class Assumption(BaseModel):
    """One value the extractor supplied rather than read.

    `target` is either a dotted plan path (`levels.L1.wall_height`) or an
    element id (`W014.thickness`). The UI resolves it to the field it should
    mark; an unresolvable target is rendered as a plan-wide note rather than
    dropped, so a slightly-off path never hides the fact that something was
    guessed.
    """

    model_config = ConfigDict(extra="ignore")

    target: str = Field(min_length=1, max_length=120)
    value: Any = None
    confidence: Confidence = Confidence.ASSUMED
    reason: str = Field(default="", max_length=300)


class Scale(BaseModel):
    """How real-world size was established, and how much to trust it.

    A plan with a printed overall dimension is trustworthy; one scaled off an
    assumed 0.9 m door is not. The grader weights its dimensional checks by
    this, because "the building is 4 m wide" is a scale error, not a geometry
    error, and re-extracting geometry will not fix it.
    """

    model_config = ConfigDict(extra="ignore")

    source: ScaleSource = ScaleSource.UNKNOWN
    # Free text: the exact evidence used, e.g. "overall dimension '20.00 m'
    # printed along the top edge".
    evidence: str = Field(default="", max_length=400)
    confidence: Confidence = Confidence.ASSUMED


class Level(_Element):
    """One storey.

    `outline` is the storey's own exterior footprint, kept per level rather than
    per plan because upper floors set back, overhang, or simply differ.
    """

    name: str = Field(min_length=1, max_length=80)
    # Absolute height of this level's finished floor. Ground floor is 0.0.
    elevation: float = Field(default=0.0, ge=-100.0, le=1000.0)
    # Floor-to-floor. The wall height is `wall_height`, which is smaller.
    floor_to_floor: float = Field(default=3.0, gt=0, le=30.0)
    wall_height: float = Field(default=2.7, gt=0, le=30.0)
    slab_thickness: float = Field(default=0.15, gt=0, le=2.0)
    outline: List[Point] = Field(default_factory=list)


class Wall(_Element):
    start: Point
    end: Point
    thickness: float = Field(default=0.15, gt=0, le=3.0)
    type: WallType = WallType.INTERIOR
    # None means "use this level's wall_height". Kept nullable rather than
    # eagerly filled so an override on the level still reaches walls that were
    # never individually set.
    height: Optional[float] = Field(default=None, gt=0, le=30.0)
    level_id: str = "L1"
    # True when the wall carries load. The extractor guesses from thickness and
    # position; the user corrects it. Drives IFC's LoadBearing property later.
    load_bearing: bool = False

    @model_validator(mode="after")
    def _non_degenerate(self) -> "Wall":
        if self.start == self.end:
            raise ValueError(f"wall {self.id}: start and end are the same point")
        return self

    @property
    def length(self) -> float:
        dx = self.end[0] - self.start[0]
        dy = self.end[1] - self.start[1]
        return (dx * dx + dy * dy) ** 0.5


class Opening(_Element):
    """A door, window or hole, hosted by exactly one wall.

    `offset` is measured along the host wall from its `start` to the opening's
    NEAR edge, so `offset + width` must not exceed the wall's length. This is
    the single most common thing an extractor gets wrong, and the grader checks
    it explicitly.
    """

    type: OpeningType
    wall_id: str
    offset: float = Field(ge=0, le=1000.0)
    width: float = Field(gt=0, le=30.0)
    height: float = Field(gt=0, le=15.0)
    # Height of the sill above this level's floor. 0 for doors.
    sill: float = Field(default=0.0, ge=0, le=10.0)

    @field_validator("wall_id")
    @classmethod
    def _well_formed_host(cls, value: str) -> str:
        value = value.strip().upper()
        if not _ID_PATTERN.match(value):
            raise ValueError(f"wall_id {value!r} is malformed")
        return value

    @model_validator(mode="after")
    def _doors_sit_on_the_floor(self) -> "Opening":
        if self.type in (OpeningType.DOOR, OpeningType.DOUBLE_DOOR, OpeningType.SLIDING_DOOR):
            # A door with a sill is a window that was mislabelled. Correct it
            # here rather than rejecting the whole plan for one bad row.
            self.sill = 0.0
        return self


class Room(_Element):
    """A named, closed area.

    `type` is free text on purpose. Room naming is the least standardised part
    of any drawing — "Drawing Room", "Majlis", "Baithak", "Lounge" are the same
    space — and a closed enum would reject plans this app is meant to accept.
    The grader normalises it for its own checks without constraining the value.
    """

    name: str = Field(min_length=1, max_length=100)
    type: str = Field(default="", max_length=60)
    polygon: List[Point] = Field(min_length=3)
    level_id: str = "L1"


class Fixture(_Element):
    """Furniture, sanitary ware, or equipment — anything placed inside a room.

    `category` is free text for the same reason `Room.type` is. The IFC builder
    maps the categories it knows onto proper IFC classes (a `wc` becomes an
    IfcSanitaryTerminal) and falls back to a generic furnishing for the rest,
    so an unrecognised category costs fidelity, never a failed build.
    """

    category: str = Field(min_length=1, max_length=60)
    position: Point  # centre
    size: Point  # (width, depth) footprint
    height: float = Field(default=0.8, gt=0, le=10.0)
    rotation: float = Field(default=0.0, ge=-360.0, le=360.0)  # degrees CCW
    room_id: str = ""
    level_id: str = "L1"


class BimPlan(BaseModel):
    """A complete, buildable description of one building.

    Every list may be empty except `levels` and `walls`: a plan with no walls
    is not a plan, and a plan with no level has nowhere to put them.
    """

    model_config = ConfigDict(extra="ignore")

    schema_version: str = SCHEMA_VERSION
    units: str = "meters"

    name: str = Field(default="", max_length=150)
    building_type: BuildingType = BuildingType.OTHER
    # What the extractor understood the drawing to be. Shown to the user as the
    # system's own reading of their plan, so a misread is visible immediately
    # rather than after they have inspected the 3D model.
    description: str = Field(default="", max_length=4000)

    scale: Scale = Field(default_factory=Scale)

    levels: List[Level] = Field(min_length=1)
    walls: List[Wall] = Field(min_length=1)
    openings: List[Opening] = Field(default_factory=list)
    rooms: List[Room] = Field(default_factory=list)
    fixtures: List[Fixture] = Field(default_factory=list)

    assumptions: List[Assumption] = Field(default_factory=list)

    @model_validator(mode="after")
    def _references_resolve(self) -> "BimPlan":
        """Reject a plan whose internal references do not resolve.

        This is a hard failure rather than a grader warning: an opening hosted
        by a wall that does not exist cannot be placed, cannot be drawn and
        cannot be edited, so letting it through only moves the crash later.
        The extractor's repair loop feeds this message back to the model.
        """
        level_ids = {level.id for level in self.levels}
        if len(level_ids) != len(self.levels):
            raise ValueError("duplicate level ids")

        wall_ids = {wall.id for wall in self.walls}
        if len(wall_ids) != len(self.walls):
            raise ValueError("duplicate wall ids")

        for wall in self.walls:
            if wall.level_id not in level_ids:
                raise ValueError(
                    f"wall {wall.id} references level {wall.level_id!r}, which does not exist"
                )

        for opening in self.openings:
            if opening.wall_id not in wall_ids:
                raise ValueError(
                    f"opening {opening.id} references wall {opening.wall_id!r}, "
                    f"which does not exist"
                )

        for room in self.rooms:
            if room.level_id not in level_ids:
                raise ValueError(
                    f"room {room.id} references level {room.level_id!r}, which does not exist"
                )

        for fixture in self.fixtures:
            if fixture.level_id not in level_ids:
                raise ValueError(
                    f"fixture {fixture.id} references level {fixture.level_id!r}, "
                    f"which does not exist"
                )

        return self

    # -- lookups ----------------------------------------------------------
    def wall_by_id(self, wall_id: str) -> Optional[Wall]:
        return next((w for w in self.walls if w.id == wall_id), None)

    def level_by_id(self, level_id: str) -> Optional[Level]:
        return next((l for l in self.levels if l.id == level_id), None)

    def openings_on(self, wall_id: str) -> List[Opening]:
        return [o for o in self.openings if o.wall_id == wall_id]

    def effective_wall_height(self, wall: Wall) -> float:
        if wall.height is not None:
            return wall.height
        level = self.level_by_id(wall.level_id)
        return level.wall_height if level else _GENERIC_DEFAULTS.wall_height
